// Code generated by hertz generator.

package main

import (
	"log"
	"github.com/yourusername/yourrepository/pkg/config" // Import for config loading

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	// Load application configuration
	if err := config.LoadConfig(); err != nil {
		log.Fatalf("Failed to load configuration: %v", err)
	}

	h := server.Default()

	register(h)
	h.Spin()
}
